default: main.cpp glm/**/*
	g++ -std=c++11 -Werror \
	-I/usr/local/Cellar/glew/2.2.0_1/include \
	-I/usr/local/Cellar/glfw/3.3.8/include \
	-L/usr/local/Cellar/glew/2.2.0_1/lib \
	-L/usr/local/Cellar/glfw/3.3.8/lib \
	-lGLEW -lglfw -framework OpenGL \
	-o main main.cpp
